backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "blog" # Usado en rutas, por ejemplo, /admin/collections/blog
    label: "Blog" # Usado en la interfaz de usuario
    folder: "src/pages/blog" # La ruta a la carpeta donde se almacenan los documentos
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    slug: "{{slug}}" # El formato del nombre del archivo
    fields: # Los campos para cada documento, generalmente al principio
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
